enable: true
night-event:
  enable: true
  time-to-next-run:  #seconds
    min: 10
    max: 40
economic-growth-event:
  enable: true
  time-to-next-run:  #seconds
    min: 10
    max: 40
  time-to-end: #seconds
    min: 10
    max: 40
gold-rush-event:
  enable: true
  multiplier: 3
  time-to-next-run: #seconds
    min: 10
    max: 40
  time-to-end: #seconds
    min: 10
    max: 40
insomnia-event:
  enable: true
  bed-coord:
    x: 15
    z: 15
  range: 3
  time-to-run: 20
  time-to-stop: 20
rain-event:
  enable: true
  time-to-next-run:  #seconds
    min: 10
    max: 40
  ritual-blocks-coord:
    1:
      x: 15
      y: 15
      z: 15
    2:
      x: 15
      y: 15
      z: 15
    3:
      x: 15
      y: 15
      z: 15