name: BlockCityTycoonEvents
version: '${project.version}'
main: me.darkmun.blockcitytycoonevents.BlockCityTycoonEvents
authors: [ Darkmun ]
depend: [ProtocolLib, PacketWrapper]
commands:
  event:
    description: Запуск или остановка ивентов
  bctevents:
    description: Для перезагрузки конфигов